cache:
  directories:
  - node_modules
language: node_js
node_js:
- '0.10'
sudo: false
deploy:
  - provider: npm
    email: slobak@gmail.com
    skip_cleanup: true
    api_key:
      secure: gHsk15gRBw+OtV4LWmmpb41+sdy/XJhZyi6ZwHNSestpVYUw667jnwEaBQQ4L1osgZf6h2ShDI7pQgSdF3WpWDZTTngQGCo5FE2dgffWGoSOje+oh9PErloTjiMg9xCnw9K1CfS7H2pEk//WUsOzBvMJREZQPMVjF3JqqoVtGNSKdxkjBFPRfwfHQCyZa8gbf+ROn74nbrsCHBmFkOjgWdl9rbPoI2oIDBT+R2PaYimVZxz/MkycAdIpUQ0FJRvCp6+nOplHKFF3/XA3oYDMItnYOn9qtup1ahNezbV8cTry+HFKTs8GUykRq9JrzdbgTVZ9h80PjKnTR/KSfZ5ZucqHiAF/ZuSuQh89CCa+EAttqxXMYPLJWWS7xJE8LI10aHy2kA9ilCceorpgz8NLfMX5EwVl69cAdnlGuVgMymdiqx1ddgtVFdj6JWx3b/w18AMP3gQC/Z2tmiJmM4KJ7vfhMHD1Mb9z9a4IjQnxcRkyAUdhDNpA9m1QbFJg5qtWiBn45OVn6bjKmp+ddLmR931bY1xyq3jzhsOb4EAJlmQRiENGsU6O82b2lyA7gRNlafnom5kknUkXA4JQS7XyhrbGBjtvWVC33LepmLO297MBL4YJexKf2rJbKZsUDvJHAGvsICGb1TSP1xsL9JNRRCrh3KlY4Iap2AB6ouozRKM=
    on:
      branch: master
      repo: Asana/node-asana-phrase
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "jv7iVFgjcUQPE8bQWHJLgfywNSkB1qsXJ4JoWvGCrB7r60nSpQt38ocNJVgKOdJHOM8TucCz7+yo+R9m4GhD0suWcOzxJnynk6yYek7gTSMvyRXG9olaacsNn7z/5sFLj7Hp2qpHlbeN0mzMRk0A+H04KCG9JSwtHWuUXfgO6I7RMmQ49wujiVX5k7AgeZubZq1JMQc8eKGEKaowKPgsqfcJ5T4hkPWSMwDPzs2oHuv6Lw/C3IMVzpPAdnsaiqi4O8aGaCqgpqO8R7CfkQWqrTbPcA7swDF0vVoNAABgPhQS2PxgV1oWcHp/buHQ1tk7si20zQ8nfG9AJoZn29UuHwMatmhwNrBvIUrM++5it1zWDhjt/w6L6v7pfQHHR+KZqj2QUeJL6tVQiIFfU93xE7mcH66Aa7+8KTPf06SJQFw3R1aIE0lYqWpSE3dl5ZxeALtQWtwD7jyDu3+6fhUCRq94Vtb8EdyitVjV1MGtNS1HydfESwtJkw3D1eggaREb2gdXpmWvXyWH70HobhrqvqJqDY6L6PGdXqm2FcCwv2xGtlx0LBguLRxo3+1igWvKgTC07BzCL4CEoprL17ZHk4ZX0/vPf35qiODwxA38SGpxVgQDT5oihjySPxFtkri21Cypk84xX66HZ+X79DotQK+weq8IBYan/UHmlc4Crxw="
    file:
      - dist/asana-phrase.js
      - dist/asana-phrase-min.js
    on:
      branch: master
      repo: Asana/node-asana-phrase
after_deploy:
- git config --global user.email "git@asana.com"
- git config --global user.name "Asana"
env:
  global:
    secure: JGg/anMqdy4Jhk+HYSM+rTdTMi1i0HKu10sn7NoKWKtqinSSEb4q5sJP19RWz/ng/sYYK5SwYY3DYRPFkVxfopVedr0Uz3by9NojNHOEr8FKN+YQMRcvqa94p9RB4SuiF8Fp405vXW4JlhBlx/YxQHcs+BKjDQT88xM8TS0iqGM=
